### ISSUE TITLE
App crashes while waiting for the "Blog" page to load

### ISSUE THREAD

**Issue by josephace135** [BoomApps-LLC/SteemApp-Android#38]
#### Expected behavior
The “Blog” page should be displayed right after logging in to SteemApp.

#### Actual behavior
Upon a successful login, the application crashes while waiting for the “Blog” page to load.

#### How to reproduce 
* Open SteemApp and log-in your Steem account.
* After logging in, wait for the “Blog” page to load and while waiting, the bug occurs wherein the app crashes.
* Additionally, when the app crash, try opening the app again and still the "Blog" page crashes after a few seconds.
* Lastly, try to uninstall and re-install the app; and repeat the previous steps, the bug still occurs.

#### Logcat Report
```
08-20 22:26:19.810  7814  7878 E AndroidRuntime: FATAL EXCEPTION: pool-12-thread-1
08-20 22:26:19.810  7814  7878 E AndroidRuntime: Process: com.boomapps.steemapp, PID: 7814
08-20 22:26:19.810  7814  7878 E AndroidRuntime: java.lang.UnsupportedOperationException: JsonNull
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at com.google.gson.JsonElement.getAsString(JsonElement.java:192)
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at com.boomapps.steemapp.repository.steem.StoryMetadataDeserializer.deserialize(StoryMetadataDeserializer.kt:32)
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at com.boomapps.steemapp.repository.steem.StoryMetadataDeserializer.deserialize(StoryMetadataDeserializer.kt:9)
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:888)
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:853)
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:802)
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:774)
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at com.boomapps.steemapp.repository.db.DiscussionToStoryMapper.parseMetadata(DiscussionToStoryMapper.kt:130)
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at com.boomapps.steemapp.repository.db.DiscussionToStoryMapper.convertToStory(DiscussionToStoryMapper.kt:52)
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at com.boomapps.steemapp.repository.db.DiscussionToStoryMapper.map(DiscussionToStoryMapper.kt:22)
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at com.boomapps.steemapp.repository.FeedBoundaryCallback$insertItemsIntoDb$1.run(FeedBoundaryCallback.kt:33)
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
08-20 22:26:19.810  7814  7878 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
```

#### Environment
* App/Plugin version: SteemApp version 2.2.4
* Device: Samsung Galaxy J2 Prime (SM-G532G/DS)
* Operating system: Android version 6.0.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=Kvfp13MdOes

**Comment by VitalyGrechikha** [comment]
Hello @josephace135 
Thank you for your report.
I made a fix for this issue and it will be included in the next app version.

FYI: it is a problem in bad value in one field in the server's answer:
Server returns :
      `"json_metadata": {
            "tags": [
                null
            ]
        }`

instead of an empty array

**Comment by josephace135** [comment]
You're welcome @VitalyGrechikha . Thank you also.
