### ISSUE TITLE
Picture not attaching 

### ISSUE THREAD

**Issue by djavalord** [BoomApps-LLC/SteemApp-Android#8]
#### Expected behavior
I expect to take picture directly from the app, and upload or choose a picture from the gallery and upload successfully 

#### Actual behavior
When I try to upload a picture taking from camera, I got an error massage that say " open app again,  and leave a feedback". When I try uploading from gallery, I got same error massage. 

#### How to reproduce
* download the app [here](https://play.google.com/store/apps/details?id=com.boomapps.steemapp)
* sign in to the app using the required details 
* click on the creat post 
* add title to the post
* click on next at the top right hand side of the app
* swipe the icons above the keyboard to see more controls
* select the last on the list which is for picture upload 
* choose take a photo 
* take a photo from the camera interface 
* click on the good (√) sign when done
* you'll see that the picture will not attach instead,  you'll get and error massage.  Thus the bug. 
* follow the above steps again, but instead of choosing take a photo , select choose from library 
* select a photo from your gallery,  then attach
* you will get same error massage. 

---
* Browser/App version: steemapp version 2.0.3
* Operating system: android  8.0 Oreo.  Tecno camon X

#### Recording Of The Bug
https://youtu.be/YLdO3-bne7E

#### GitHub Account
https://github.com/djavalord

**Comment by tobias-g1** [comment]
Find log of the crash below when replicated on Android 6.0.3, Version 2.0.3

```
06-30 11:46:49.378 24576-25240/com.boomapps.steemapp E/SteemRepositoryDefault: Image upload exception
    com.google.api.client.http.HttpResponseException: 500 Internal Server Error
    {"error":{"name":"internal_error"}}
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)
        at eu.bittrade.libs.steemj.image.upload.SteemJImageUpload.executeMultipartRequest(SteemJImageUpload.java:171)
        at eu.bittrade.libs.steemj.image.upload.SteemJImageUpload.uploadImage(SteemJImageUpload.java:128)
        at com.boomapps.steemapp.repository.steem.SteemRepositoryDefault.uploadImage(SteemRepositoryDefault.kt:207)
        at com.boomapps.steemapp.repository.network.NetworkRepositoryDefault$uploadNewPhoto$1.call(NetworkRepositoryDefault.kt:100)
        at com.boomapps.steemapp.repository.network.NetworkRepositoryDefault$uploadNewPhoto$1.call(NetworkRepositoryDefault.kt:35)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:10955)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
06-30 11:46:49.420 24576-24576/com.boomapps.steemapp E/UncaughtException: io.reactivex.exceptions.OnErrorNotImplementedException: Callable returned null
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onError(ObservableDoOnEach.java:119)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onError(ObservableDoOnEach.java:119)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onError(ObservableDoOnEach.java:119)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
        at android.os.Handler.handleCallback(Handler.java:746)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: java.lang.NullPointerException: Callable returned null
        at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:10955)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
06-30 11:46:49.724 24576-24576/com.boomapps.steemapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.boomapps.steemapp, PID: 24576
    io.reactivex.exceptions.OnErrorNotImplementedException: Callable returned null
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onError(ObservableDoOnEach.java:119)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onError(ObservableDoOnEach.java:119)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onError(ObservableDoOnEach.java:119)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
        at android.os.Handler.handleCallback(Handler.java:746)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: java.lang.NullPointerException: Callable returned null
        at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:10955)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by djavalord** [comment]
Thanks for the log cats

**Comment by BoomAppsLLC** [comment]
#3 
Thank you, guys, for bug reporting. Later we will fix it

**Comment by djavalord** [comment]
We hope to see it fixed as soon as possible so that we can continue to enjoy every single feature of this great app
